apiVersion: v1
kind: Template
metadata:
  name: build-analysers-buildconfig
  labels:
    template: build-analysers-buildconfig
    app: thoth
    component: build-analyser
  annotations:
    description: >
      This is Thoth Build Analysers API BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    openshift.io/display-name: Thoth Build Analysers API BuildConfig
    version: 0.2.0
    tags: poc,thoth,build-analysers,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This is Thoth Build Analysers API BuildConfig, this template is meant to be used by Bots,
      but could also be used by humans...
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: thoth
        component: build-analyser
      name: build-analysers
    spec:
      name: ${IMAGE_STREAM_TAG}

  - apiVersion: v1
    kind: BuildConfig
    metadata:
      name: build-analysers
      labels:
        app: thoth-core
        component: build-analyser
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: "build-analysers:${IMAGE_STREAM_TAG}"
      source:
        type: Git
        git:
          uri: ${GITHUB_URL}
          ref: ${GITHUB_REF}
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: python-36-centos7:latest
          env:
            - name: ENABLE_PIPENV
              value: "1"
      triggers:
        - type: ImageChange
          imageChange: {}

parameters:
  - description: Git repository for Thoth's Build Analysers
    displayName: Thoth build-analysers git repository
    required: true
    name: GITHUB_URL
    value: 'https://github.com/thoth-station/build-analysers'

  - description: Git repository for Thoth's Build Analysers API
    displayName: Thoth build-analysers git reference
    required: true
    name: GITHUB_REF
    value: 'master'

  - description: Tag of the output ImageStream the resulting container image should go to
    displayName: ImageStream Tag
    required: true
    name: IMAGE_STREAM_TAG
    value: 'latest'
