apiVersion: v1
kind: Template
metadata:
  name: build-analysers
  labels:
    template: build-analysers
    app: thoth
    component: build-analyser
  annotations:
    description: >
      This is Thoth Core - Build Analyser
    openshift.io/display-name: Thoth Core
    version: 0.2.0
    tags: poc,thoth,ai-stacks,build-analysers
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Core Services as a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        service: build-analyser
        app: thoth
        component: build-analyser
      name: build-analyser
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        service: build-analyser

  - kind: Route
    apiVersion: v1
    metadata:
      name: build-analyser
      labels:
        app: thoth
        component: build-analyser
    spec:
      to:
        kind: Service
        name: build-analyser

  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        service: build-analyser
        app: thoth-core
        component: build-analyser
      name: build-analyser
    spec:
      replicas: 1
      selector:
        service: build-analyser
      template:
        metadata:
          labels:
            service: build-analyser
            app: thoth
            component: build-analyser
        spec:
          containers:
            - name: build-analyser
              env:
                - name: THOTH_DEPLOYMENT_NAME
                  valueFrom:
                    configMapKeyRef:
                      key: storage-bucket-name
                      name: thoth
                - name: THOTH_CEPH_HOST
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-host
                      name: thoth
                - name: THOTH_CEPH_BUCKET
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-name
                      name: thoth
                - name: THOTH_CEPH_BUCKET_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      key: ceph-bucket-prefix
                      name: thoth
                - name: THOTH_CEPH_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-key-id
                - name: THOTH_CEPH_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: thoth
                      key: ceph-secret-key
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "125m"
                limits:
                  memory: "256Mi"
                  cpu: "500m"
              readinessProbe:
                httpGet:
                  path: '/readiness'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 10
                timeoutSeconds: 10
              livenessProbe:
                httpGet:
                  path: '/liveness'
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                periodSeconds: 60
                timeoutSeconds: 10
      test: false
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - build-analyser
            from:
              kind: ImageStreamTag
              name: 'build-analusers-api:latest'
